Sample launch file for melodic
ros-perception/depthimage_to_laserscan pull request #55
Opened 2021-09-02 08:35 UTC by paulacvalle

Sample launch file with all parameters listed with default values.
Also includes a quick fix to issues with remapping the camera_info topic.
I hope this might be useful for another beginner!

All the best,
Paula.

2021-09-02 13:04 UTC, clalancette requested changes
Thanks for the contribution.  I've put some comments below.

Besides what I've pointed out inline, we should also put this file in a `launch` subdirectory.

2021-09-02 13:04 UTC, clalancette commented on launchfile_sample.launch
> +	SAMPLE LAUNCH FILE FOR depthimage_to_laserscan for ROS melodic
```suggestion
	Sample launch file for depthimage_to_laserscan
```

2021-09-02 13:04 UTC, clalancette commented on launchfile_sample.launch
> +	<node  name="depthimage_to_laserscan" pkg="depthimage_to_laserscan" type="depthimage_to_laserscan" args="">
The indentation (here and below) is inconsistent.  Let's use a consistent 2 spaces for indentation for all levels of the XML.

2021-09-02 13:04 UTC, clalancette commented on launchfile_sample.launch
> +		<!-- the remap for camera_info can present issues, and by default uses the same path as the one given to the image topic. Default: "<path_to_image_topic>/camera_info>" -->
```suggestion
		<!-- the remap for camera_info by default uses the same path as the one given to the image topic. Default: "<path_to_image_topic>/camera_info>" -->
```

2021-09-02 13:04 UTC, clalancette commented on launchfile_sample.launch
> +
Remove one of these two spaces.

2021-09-02 13:04 UTC, clalancette commented on launchfile_sample.launch
> +		<!-- These are the default values. You can remove the lines you are not using. More information on the ROS wiki page -->
```suggestion
		<!-- These are the default values. --> 
```

2021-09-02 13:04 UTC, clalancette commented on launchfile_sample.launch
> +	-->
Let's just remove this.

2021-09-03 09:00 UTC, paulacvalle commented
> Thanks for the contribution. I've put some comments below.
> 
> Besides what I've pointed out inline, we should also put this file in a `launch` subdirectory.

I will make the changes. Thank you for taking the time to reply, I am learning on how to contribute to bigger repositories from this experience!

2021-09-03 12:23 UTC, clalancette approved these changes
I went ahead and changed all tabs to spaces; layouts look more consistent in different editors with spaces.

Otherwise, this looks good to me.  Thanks for the contribution, I'll go ahead and merge this.

2021-09-03 12:24 UTC, merged